version: "3.8"

services:
  web:
    build: .
    platform: linux/amd64 # Garantir a compatibilidade da plataforma
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0 # Usando a versão mais recente do MySQL
    platform: linux/amd64 # Garantir a compatibilidade da plataforma
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contacts
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data: # Definindo o volume persistente para os dados do MySQL

networks:
  app-network:
    driver: bridge # Configuração de rede personalizada
